// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gradient.proto

#include "gradient.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace gradient {
template <typename>
PROTOBUF_CONSTEXPR GradientRequest::GradientRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.gradients_)*/ {}

  , /*decltype(_impl_.worker_id_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GradientRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GradientRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GradientRequestDefaultTypeInternal() {}
  union {
    GradientRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GradientRequestDefaultTypeInternal _GradientRequest_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR GradientReply::GradientReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GradientReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GradientReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GradientReplyDefaultTypeInternal() {}
  union {
    GradientReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GradientReplyDefaultTypeInternal _GradientReply_default_instance_;
}  // namespace gradient
static ::_pb::Metadata file_level_metadata_gradient_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_gradient_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gradient_2eproto = nullptr;
const ::uint32_t TableStruct_gradient_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::gradient::GradientRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::gradient::GradientRequest, _impl_.gradients_),
    PROTOBUF_FIELD_OFFSET(::gradient::GradientRequest, _impl_.worker_id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::gradient::GradientReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::gradient::GradientReply, _impl_.status_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::gradient::GradientRequest)},
        { 10, -1, -1, sizeof(::gradient::GradientReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::gradient::_GradientRequest_default_instance_._instance,
    &::gradient::_GradientReply_default_instance_._instance,
};
const char descriptor_table_protodef_gradient_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016gradient.proto\022\010gradient\"7\n\017GradientRe"
    "quest\022\021\n\tgradients\030\001 \003(\002\022\021\n\tworker_id\030\002 "
    "\001(\t\"\037\n\rGradientReply\022\016\n\006status\030\001 \001(\t2U\n\017"
    "GradientService\022B\n\014SendGradient\022\031.gradie"
    "nt.GradientRequest\032\027.gradient.GradientRe"
    "plyb\006proto3"
};
static ::absl::once_flag descriptor_table_gradient_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_gradient_2eproto = {
    false,
    false,
    211,
    descriptor_table_protodef_gradient_2eproto,
    "gradient.proto",
    &descriptor_table_gradient_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_gradient_2eproto::offsets,
    file_level_metadata_gradient_2eproto,
    file_level_enum_descriptors_gradient_2eproto,
    file_level_service_descriptors_gradient_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_gradient_2eproto_getter() {
  return &descriptor_table_gradient_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_gradient_2eproto(&descriptor_table_gradient_2eproto);
namespace gradient {
// ===================================================================

class GradientRequest::_Internal {
 public:
};

GradientRequest::GradientRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gradient.GradientRequest)
}
GradientRequest::GradientRequest(const GradientRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GradientRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.gradients_) { from._impl_.gradients_ }

    , decltype(_impl_.worker_id_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_worker_id().empty()) {
    _this->_impl_.worker_id_.Set(from._internal_worker_id(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:gradient.GradientRequest)
}

inline void GradientRequest::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.gradients_) { arena }

    , decltype(_impl_.worker_id_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GradientRequest::~GradientRequest() {
  // @@protoc_insertion_point(destructor:gradient.GradientRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GradientRequest::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.gradients_.~RepeatedField();
  _impl_.worker_id_.Destroy();
}

void GradientRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GradientRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:gradient.GradientRequest)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_gradients()->Clear();
  _impl_.worker_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GradientRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float gradients = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_gradients(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::uint8_t>(tag) == 13) {
          _internal_add_gradients(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // string worker_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_worker_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gradient.GradientRequest.worker_id"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* GradientRequest::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gradient.GradientRequest)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float gradients = 1;
  if (this->_internal_gradients_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_gradients(), target);
  }

  // string worker_id = 2;
  if (!this->_internal_worker_id().empty()) {
    const std::string& _s = this->_internal_worker_id();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "gradient.GradientRequest.worker_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gradient.GradientRequest)
  return target;
}

::size_t GradientRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gradient.GradientRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float gradients = 1;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_gradients_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }

  // string worker_id = 2;
  if (!this->_internal_worker_id().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_worker_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GradientRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GradientRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GradientRequest::GetClassData() const { return &_class_data_; }


void GradientRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GradientRequest*>(&to_msg);
  auto& from = static_cast<const GradientRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gradient.GradientRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.gradients_.MergeFrom(from._impl_.gradients_);
  if (!from._internal_worker_id().empty()) {
    _this->_internal_set_worker_id(from._internal_worker_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GradientRequest::CopyFrom(const GradientRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gradient.GradientRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GradientRequest::IsInitialized() const {
  return true;
}

void GradientRequest::InternalSwap(GradientRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.gradients_.InternalSwap(&other->_impl_.gradients_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.worker_id_, lhs_arena,
                                       &other->_impl_.worker_id_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata GradientRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gradient_2eproto_getter, &descriptor_table_gradient_2eproto_once,
      file_level_metadata_gradient_2eproto[0]);
}
// ===================================================================

class GradientReply::_Internal {
 public:
};

GradientReply::GradientReply(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gradient.GradientReply)
}
GradientReply::GradientReply(const GradientReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GradientReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.status_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_status().empty()) {
    _this->_impl_.status_.Set(from._internal_status(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:gradient.GradientReply)
}

inline void GradientReply::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.status_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.status_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GradientReply::~GradientReply() {
  // @@protoc_insertion_point(destructor:gradient.GradientReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GradientReply::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.status_.Destroy();
}

void GradientReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GradientReply::Clear() {
// @@protoc_insertion_point(message_clear_start:gradient.GradientReply)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GradientReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_status();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gradient.GradientReply.status"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* GradientReply::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gradient.GradientReply)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    const std::string& _s = this->_internal_status();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "gradient.GradientReply.status");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gradient.GradientReply)
  return target;
}

::size_t GradientReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gradient.GradientReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GradientReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GradientReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GradientReply::GetClassData() const { return &_class_data_; }


void GradientReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GradientReply*>(&to_msg);
  auto& from = static_cast<const GradientReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gradient.GradientReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GradientReply::CopyFrom(const GradientReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gradient.GradientReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GradientReply::IsInitialized() const {
  return true;
}

void GradientReply::InternalSwap(GradientReply* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, lhs_arena,
                                       &other->_impl_.status_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata GradientReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gradient_2eproto_getter, &descriptor_table_gradient_2eproto_once,
      file_level_metadata_gradient_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace gradient
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gradient::GradientRequest*
Arena::CreateMaybeMessage< ::gradient::GradientRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gradient::GradientRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::gradient::GradientReply*
Arena::CreateMaybeMessage< ::gradient::GradientReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gradient::GradientReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
