// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gradient.proto

#include "gradient.pb.h"
#include "gradient.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace gradient {

static const char* GradientService_method_names[] = {
  "/gradient.GradientService/StreamGradients",
};

std::unique_ptr< GradientService::Stub> GradientService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GradientService::Stub> stub(new GradientService::Stub(channel, options));
  return stub;
}

GradientService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamGradients_(GradientService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::gradient::GradientRequest>* GradientService::Stub::StreamGradientsRaw(::grpc::ClientContext* context, ::gradient::GradientReply* response) {
  return ::grpc::internal::ClientWriterFactory< ::gradient::GradientRequest>::Create(channel_.get(), rpcmethod_StreamGradients_, context, response);
}

void GradientService::Stub::async::StreamGradients(::grpc::ClientContext* context, ::gradient::GradientReply* response, ::grpc::ClientWriteReactor< ::gradient::GradientRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::gradient::GradientRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamGradients_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::gradient::GradientRequest>* GradientService::Stub::AsyncStreamGradientsRaw(::grpc::ClientContext* context, ::gradient::GradientReply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::gradient::GradientRequest>::Create(channel_.get(), cq, rpcmethod_StreamGradients_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::gradient::GradientRequest>* GradientService::Stub::PrepareAsyncStreamGradientsRaw(::grpc::ClientContext* context, ::gradient::GradientReply* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::gradient::GradientRequest>::Create(channel_.get(), cq, rpcmethod_StreamGradients_, context, response, false, nullptr);
}

GradientService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GradientService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< GradientService::Service, ::gradient::GradientRequest, ::gradient::GradientReply>(
          [](GradientService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::gradient::GradientRequest>* reader,
             ::gradient::GradientReply* resp) {
               return service->StreamGradients(ctx, reader, resp);
             }, this)));
}

GradientService::Service::~Service() {
}

::grpc::Status GradientService::Service::StreamGradients(::grpc::ServerContext* context, ::grpc::ServerReader< ::gradient::GradientRequest>* reader, ::gradient::GradientReply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gradient

