// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gradient.proto

#include "gradient.pb.h"
#include "gradient.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace gradient {

static const char* GradientService_method_names[] = {
  "/gradient.GradientService/SendGradient",
};

std::unique_ptr< GradientService::Stub> GradientService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GradientService::Stub> stub(new GradientService::Stub(channel, options));
  return stub;
}

GradientService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendGradient_(GradientService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GradientService::Stub::SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::gradient::GradientReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gradient::GradientRequest, ::gradient::GradientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendGradient_, context, request, response);
}

void GradientService::Stub::async::SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gradient::GradientRequest, ::gradient::GradientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendGradient_, context, request, response, std::move(f));
}

void GradientService::Stub::async::SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendGradient_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>* GradientService::Stub::PrepareAsyncSendGradientRaw(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gradient::GradientReply, ::gradient::GradientRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendGradient_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>* GradientService::Stub::AsyncSendGradientRaw(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendGradientRaw(context, request, cq);
  result->StartCall();
  return result;
}

GradientService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GradientService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GradientService::Service, ::gradient::GradientRequest, ::gradient::GradientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GradientService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gradient::GradientRequest* req,
             ::gradient::GradientReply* resp) {
               return service->SendGradient(ctx, req, resp);
             }, this)));
}

GradientService::Service::~Service() {
}

::grpc::Status GradientService::Service::SendGradient(::grpc::ServerContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gradient

