// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gradient.proto
#ifndef GRPC_gradient_2eproto__INCLUDED
#define GRPC_gradient_2eproto__INCLUDED

#include "gradient.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace gradient {

class GradientService final {
 public:
  static constexpr char const* service_full_name() {
    return "gradient.GradientService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::gradient::GradientReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gradient::GradientReply>> AsyncSendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gradient::GradientReply>>(AsyncSendGradientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gradient::GradientReply>> PrepareAsyncSendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gradient::GradientReply>>(PrepareAsyncSendGradientRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gradient::GradientReply>* AsyncSendGradientRaw(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gradient::GradientReply>* PrepareAsyncSendGradientRaw(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::gradient::GradientReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>> AsyncSendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>>(AsyncSendGradientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>> PrepareAsyncSendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>>(PrepareAsyncSendGradientRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response, std::function<void(::grpc::Status)>) override;
      void SendGradient(::grpc::ClientContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>* AsyncSendGradientRaw(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gradient::GradientReply>* PrepareAsyncSendGradientRaw(::grpc::ClientContext* context, const ::gradient::GradientRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendGradient_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendGradient(::grpc::ServerContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendGradient() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendGradient(::grpc::ServerContext* /*context*/, const ::gradient::GradientRequest* /*request*/, ::gradient::GradientReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendGradient(::grpc::ServerContext* context, ::gradient::GradientRequest* request, ::grpc::ServerAsyncResponseWriter< ::gradient::GradientReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendGradient<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendGradient() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::gradient::GradientRequest, ::gradient::GradientReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gradient::GradientRequest* request, ::gradient::GradientReply* response) { return this->SendGradient(context, request, response); }));}
    void SetMessageAllocatorFor_SendGradient(
        ::grpc::MessageAllocator< ::gradient::GradientRequest, ::gradient::GradientReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gradient::GradientRequest, ::gradient::GradientReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendGradient(::grpc::ServerContext* /*context*/, const ::gradient::GradientRequest* /*request*/, ::gradient::GradientReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendGradient(
      ::grpc::CallbackServerContext* /*context*/, const ::gradient::GradientRequest* /*request*/, ::gradient::GradientReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendGradient<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendGradient() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendGradient(::grpc::ServerContext* /*context*/, const ::gradient::GradientRequest* /*request*/, ::gradient::GradientReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendGradient() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendGradient(::grpc::ServerContext* /*context*/, const ::gradient::GradientRequest* /*request*/, ::gradient::GradientReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendGradient(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendGradient() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendGradient(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendGradient(::grpc::ServerContext* /*context*/, const ::gradient::GradientRequest* /*request*/, ::gradient::GradientReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendGradient(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendGradient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendGradient() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gradient::GradientRequest, ::gradient::GradientReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gradient::GradientRequest, ::gradient::GradientReply>* streamer) {
                       return this->StreamedSendGradient(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendGradient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendGradient(::grpc::ServerContext* /*context*/, const ::gradient::GradientRequest* /*request*/, ::gradient::GradientReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendGradient(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gradient::GradientRequest,::gradient::GradientReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendGradient<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendGradient<Service > StreamedService;
};

}  // namespace gradient


#endif  // GRPC_gradient_2eproto__INCLUDED
